export type FluidLiteQuality =
  | "off"
  | "low"
  | "medium"
  | "high"
  | "cinematic";

export type FluidLiteConfig = {
  simResolution: number;
  dyeResolution: number;
  pressureIterations: number;
  diffusionIterations: number;
  maxActiveSplats: number;
  maxSplatsPerSecond: number;
  interactionRadiusScale: number;
  effectScale: number;
  splatRadius: number;
  clickSplatRadius: number;
  splatForce: number;
  clickSplatForce: number;
  velocityScale: number;
  advectionScale: number;
  densityDissipation: number;
  velocityDissipation: number;
  pressureDissipation: number;
  dyeDiffusion: number;
  dispersionStrength: number;
  particleCount: number;
  particleSize: number;
  particleOpacity: number;
  particleDecay: number;
  displayOpacity: number;
  displayLayerOpacity: number;
  fieldBleedPx: number;
  dyeColorGain: number;
  dyeChromaBoost: number;
  dyeContrast: number;
  baseWaterOpacity: number;
  activeDyeOpacity: number;
  particleColorGain: number;
  dyeInjectionGain: number;
  maxDpr: number;
  simulationFps: number;
  autoSplatIntervalMs: number;
  autoCurrentEnabled: boolean;
  autoCurrentStrength: number;
  autoCurrentRadius: number;
  autoCurrentRotationSpeed: number;
  autoCurrentRecoverySpeed: number;
  autoCurrentDyeRate: number;
  autoCurrentLobeRadius: number;
  autoCurrentLobeSpread: number;
  autoCurrentCenterPull: number;
  autoCurrentSplatsPerSecond: number;
  userDisruptionStrength: number;
  userDisruptionRecoverySeconds: number;
};

export const fluidLitePresets: Record<FluidLiteQuality, FluidLiteConfig> = {
  off: {
    simResolution: 1,
    dyeResolution: 1,
    pressureIterations: 0,
    diffusionIterations: 0,
    maxActiveSplats: 0,
    maxSplatsPerSecond: 0,
    interactionRadiusScale: 1,
    effectScale: 0,
    splatRadius: 0,
    clickSplatRadius: 0,
    splatForce: 0,
    clickSplatForce: 0,
    velocityScale: 0,
    advectionScale: 0,
    densityDissipation: 1,
    velocityDissipation: 1,
    pressureDissipation: 1,
    dyeDiffusion: 0,
    dispersionStrength: 0,
    particleCount: 0,
    particleSize: 0,
    particleOpacity: 0,
    particleDecay: 1,
    displayOpacity: 0,
    displayLayerOpacity: 0,
    fieldBleedPx: 0,
    dyeColorGain: 0,
    dyeChromaBoost: 1,
    dyeContrast: 1,
    baseWaterOpacity: 0,
    activeDyeOpacity: 0,
    particleColorGain: 1,
    dyeInjectionGain: 0,
    maxDpr: 1,
    simulationFps: 0,
    autoSplatIntervalMs: 0,
    autoCurrentEnabled: false,
    autoCurrentStrength: 0,
    autoCurrentRadius: 0,
    autoCurrentRotationSpeed: 0,
    autoCurrentRecoverySpeed: 0,
    autoCurrentDyeRate: 0,
    autoCurrentLobeRadius: 0,
    autoCurrentLobeSpread: 0,
    autoCurrentCenterPull: 0,
    autoCurrentSplatsPerSecond: 0,
    userDisruptionStrength: 0,
    userDisruptionRecoverySeconds: 0,
  },
  low: {
    simResolution: 64,
    dyeResolution: 256,
    pressureIterations: 4,
    diffusionIterations: 1,
    maxActiveSplats: 6,
    maxSplatsPerSecond: 5,
    interactionRadiusScale: 1.6,
    effectScale: 1,
    splatRadius: 0.007,
    clickSplatRadius: 0.012,
    splatForce: 520,
    clickSplatForce: 880,
    velocityScale: 0.28,
    advectionScale: 0.1,
    densityDissipation: 0.998,
    velocityDissipation: 0.992,
    pressureDissipation: 0.945,
    dyeDiffusion: 0.0008,
    dispersionStrength: 0.28,
    particleCount: 96,
    particleSize: 1.6,
    particleOpacity: 0.26,
    particleDecay: 0.996,
    displayOpacity: 0.62,
    displayLayerOpacity: 0.88,
    fieldBleedPx: 22,
    dyeColorGain: 1.28,
    dyeChromaBoost: 1.12,
    dyeContrast: 1.06,
    baseWaterOpacity: 0.14,
    activeDyeOpacity: 0.68,
    particleColorGain: 1.12,
    dyeInjectionGain: 1.12,
    maxDpr: 1,
    simulationFps: 30,
    autoSplatIntervalMs: 5600,
    autoCurrentEnabled: true,
    autoCurrentStrength: 0.22,
    autoCurrentRadius: 0.15,
    autoCurrentRotationSpeed: 0.028,
    autoCurrentRecoverySpeed: 0.5,
    autoCurrentDyeRate: 0.09,
    autoCurrentLobeRadius: 0.024,
    autoCurrentLobeSpread: 0.044,
    autoCurrentCenterPull: 0.12,
    autoCurrentSplatsPerSecond: 3,
    userDisruptionStrength: 0.75,
    userDisruptionRecoverySeconds: 2.8,
  },
  medium: {
    simResolution: 96,
    dyeResolution: 384,
    pressureIterations: 6,
    diffusionIterations: 2,
    maxActiveSplats: 6,
    maxSplatsPerSecond: 6,
    interactionRadiusScale: 4.2,
    effectScale: 1,
    splatRadius: 0.01,
    clickSplatRadius: 0.017,
    splatForce: 760,
    clickSplatForce: 1120,
    velocityScale: 0.36,
    advectionScale: 0.105,
    densityDissipation: 0.99835,
    velocityDissipation: 0.9935,
    pressureDissipation: 0.95,
    dyeDiffusion: 0.00125,
    dispersionStrength: 0.42,
    particleCount: 168,
    particleSize: 1.7,
    particleOpacity: 0.3,
    particleDecay: 0.9975,
    displayOpacity: 0.74,
    displayLayerOpacity: 0.94,
    fieldBleedPx: 32,
    dyeColorGain: 1.42,
    dyeChromaBoost: 1.18,
    dyeContrast: 1.1,
    baseWaterOpacity: 0.18,
    activeDyeOpacity: 0.78,
    particleColorGain: 1.2,
    dyeInjectionGain: 1.2,
    maxDpr: 1.1,
    simulationFps: 30,
    autoSplatIntervalMs: 6200,
    autoCurrentEnabled: true,
    autoCurrentStrength: 0.26,
    autoCurrentRadius: 0.16,
    autoCurrentRotationSpeed: 0.03,
    autoCurrentRecoverySpeed: 0.54,
    autoCurrentDyeRate: 0.11,
    autoCurrentLobeRadius: 0.025,
    autoCurrentLobeSpread: 0.048,
    autoCurrentCenterPull: 0.14,
    autoCurrentSplatsPerSecond: 5,
    userDisruptionStrength: 0.85,
    userDisruptionRecoverySeconds: 3,
  },
  high: {
    simResolution: 160,
    dyeResolution: 640,
    pressureIterations: 20,
    diffusionIterations: 4,
    maxActiveSplats: 6,
    maxSplatsPerSecond: 6,
    interactionRadiusScale: 6,
    effectScale: 4,
    splatRadius: 0.01,
    clickSplatRadius: 0.017,
    splatForce: 760,
    clickSplatForce: 1180,
    velocityScale: 0.38,
    advectionScale: 0.125,
    densityDissipation: 0.99915,
    velocityDissipation: 0.996,
    pressureDissipation: 0.972,
    dyeDiffusion: 0.0012,
    dispersionStrength: 0.48,
    particleCount: 220,
    particleSize: 1.6,
    particleOpacity: 0.28,
    particleDecay: 0.999,
    displayOpacity: 0.78,
    displayLayerOpacity: 0.96,
    fieldBleedPx: 42,
    dyeColorGain: 1.68,
    dyeChromaBoost: 1.26,
    dyeContrast: 1.14,
    baseWaterOpacity: 0.18,
    activeDyeOpacity: 0.86,
    particleColorGain: 1.25,
    dyeInjectionGain: 1.25,
    maxDpr: 1.2,
    simulationFps: 45,
    autoSplatIntervalMs: 6800,
    autoCurrentEnabled: true,
    autoCurrentStrength: 0.3,
    autoCurrentRadius: 0.165,
    autoCurrentRotationSpeed: 0.032,
    autoCurrentRecoverySpeed: 0.58,
    autoCurrentDyeRate: 0.14,
    autoCurrentLobeRadius: 0.026,
    autoCurrentLobeSpread: 0.05,
    autoCurrentCenterPull: 0.15,
    autoCurrentSplatsPerSecond: 8,
    userDisruptionStrength: 0.9,
    userDisruptionRecoverySeconds: 3.2,
  },
  cinematic: {
    simResolution: 192,
    dyeResolution: 768,
    pressureIterations: 20,
    diffusionIterations: 4,
    maxActiveSplats: 10,
    maxSplatsPerSecond: 10,
    interactionRadiusScale: 5,
    effectScale: 1.45,
    splatRadius: 0.01,
    clickSplatRadius: 0.017,
    splatForce: 820,
    clickSplatForce: 1280,
    velocityScale: 0.34,
    advectionScale: 0.115,
    densityDissipation: 0.9986,
    velocityDissipation: 0.9935,
    pressureDissipation: 0.955,
    dyeDiffusion: 0.00125,
    dispersionStrength: 0.46,
    particleCount: 280,
    particleSize: 1.55,
    particleOpacity: 0.28,
    particleDecay: 0.9976,
    displayOpacity: 0.76,
    displayLayerOpacity: 0.96,
    fieldBleedPx: 44,
    dyeColorGain: 1.85,
    dyeChromaBoost: 1.34,
    dyeContrast: 1.18,
    baseWaterOpacity: 0.18,
    activeDyeOpacity: 0.9,
    particleColorGain: 1.3,
    dyeInjectionGain: 1.38,
    maxDpr: 1.2,
    simulationFps: 45,
    autoSplatIntervalMs: 7400,
    autoCurrentEnabled: true,
    autoCurrentStrength: 0.32,
    autoCurrentRadius: 0.17,
    autoCurrentRotationSpeed: 0.032,
    autoCurrentRecoverySpeed: 0.65,
    autoCurrentDyeRate: 0.16,
    autoCurrentLobeRadius: 0.026,
    autoCurrentLobeSpread: 0.052,
    autoCurrentCenterPull: 0.16,
    autoCurrentSplatsPerSecond: 10,
    userDisruptionStrength: 1,
    userDisruptionRecoverySeconds: 3.8,
  },
};

export const fluidSplatColors = {
  water: [0.54, 0.94, 1.0],
  electricBlue: [0.1, 0.46, 1.0],
  jade: [0.92, 0.94, 0.9],
  silverWhite: [0.92, 0.94, 0.9],
  gold: [1.0, 0.76, 0.2],
} as const;
